/// Flutter icons Mute
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Mute
///      fonts:
///       - asset: fonts/Mute.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class Mute {
  Mute._();

  static const _kFontFam = 'Mute';
  static const String? _kFontPkg = null;

  static const IconData volume_off = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_low = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
