// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFfFVLFMXVEUznVDvcR2xPmWTIAfyfU8s',
    appId: '1:358048944657:web:01e14911f14440568c17b0',
    messagingSenderId: '358048944657',
    projectId: 'codev-cs',
    authDomain: 'codev-cs.firebaseapp.com',
    databaseURL:
        'https://codev-cs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codev-cs.appspot.com',
    measurementId: 'G-VWTQ2KN0ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8LIjb-vxYyM1nHU4WMwjDyOOGiFlTqWM',
    appId: '1:358048944657:android:229fc466bedfb1ce8c17b0',
    messagingSenderId: '358048944657',
    projectId: 'codev-cs',
    databaseURL:
        'https://codev-cs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codev-cs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvCEzPh7ZxASpgeZljTRoa4j6u6M8ylP4',
    appId: '1:358048944657:ios:0f91878a532599fd8c17b0',
    messagingSenderId: '358048944657',
    projectId: 'codev-cs',
    databaseURL:
        'https://codev-cs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codev-cs.appspot.com',
    iosClientId:
        '358048944657-imgsofej9cqls3vcc094jedrhqn8bas8.apps.googleusercontent.com',
    iosBundleId: 'com.example.codev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvCEzPh7ZxASpgeZljTRoa4j6u6M8ylP4',
    appId: '1:358048944657:ios:0615741c4f8827de8c17b0',
    messagingSenderId: '358048944657',
    projectId: 'codev-cs',
    databaseURL:
        'https://codev-cs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codev-cs.appspot.com',
    iosClientId:
        '358048944657-le118inhlujb6ttqu314l6pc1lqc18s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.codev.RunnerTests',
  );
}
